version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: quiz-api-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: quiz-api
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - quiz-api-network

volumes:
  mongodb_data:
    driver: local

networks:
  quiz-api-network:
    driver: bridge
